Repository mautic/docker-mautic, pull requests merged in 2025-05, with the labels that each got.

#354 README improvements
  README.md
Labels: documentation

#357 chore: update README for docker commands
  README.md
Labels: documentation

#363 PHP amqp bump to v2.1.2
  apache/Dockerfile
  fpm/Dockerfile
Labels: hardening

#367 Enable SAST to test PRs
  .github/workflows/pr-test.yml
  .github/workflows/test.yml
Labels: hardening

#365 Add Security Policy and Community Health files
  .github/funding.yml
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  SECURITY.md
Labels: hardening, documentation

#377 Issue Templates
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature.yml
  README.md
Labels: documentation

#361 Add Composer and Node.js 22 to Docker images
  apache/Dockerfile
  fpm/Dockerfile
Labels: waiting issuer feedback

#380 fix: Set correct ownership for /var/www/html/var/cache
  apache/Dockerfile
  fpm/Dockerfile
Labels: needs test

#397 Add Trivy to Publish Pipeline
  .github/workflows/build_publish.yml
Labels: hardening
